### ISSUE TITLE
Provide JDK 21 Base Image, or a "Floating JDK" base image.

### ISSUE THREAD

**Issue by billkable** [vmware-tanzu-labs/educates-training-platform#255]
### Is your feature request related to a problem? Please describe.

Latest versions of Spring use Virtual Threads features of JDK 21, which is not currently supported directly in a base image.

### Describe the solution you'd like

Provide a base image similar to existing jdk 8, 11, 17 images, or perhaps a "floating" image that has multiple jdks installed, with the ability to pre-select the desired installed version on workshop session startup.

### Describe alternatives you've considered

Spring Academy has set up a course and some guides using SDK Man to manage multiple JDKs (particularly useful for GraalVM, or Spring-with-java version upgrades).

We handle installation of sdk man as setup.d hooked install, but would nice if this were part of a base image.

**Comment by GrahamDumpleton** [comment]
A jdk21-environment image is easy enough and follows existing path take for Java images.

A single image which has multiple Java versions would be too big and could cause issues as a result.

Another thing we should investigate just to see how practical it is, is use of extension package to package Java runtime. This will still be a large download, but could be paired with the [shared OCI image cache](https://docs.educates.dev/custom-resources/workshop-definition#shared-oci-image-cache) to try and keep any downloads local to the cluster. This may work well enough in order to allow use of JDK 21 before a jdk21-environment base image can be integrated into a release.

**Comment by billkable** [comment]
> Another thing we should investigate just to see how practical it is, is use of extension package to package Java runtime. This will still be a large download, but could be paired with the [shared OCI image cache](https://docs.educates.dev/custom-resources/workshop-definition#shared-oci-image-cache) to try and keep any downloads local to the cluster. 

> This may work well enough in order to allow use of JDK 21 before a jdk21-environment base image can be integrated into a release.

@GrahamDumpleton do you see this option as short term workaround?  We do have a workaround with SDK Man that would suffice until getting a new base image.

**Comment by GrahamDumpleton** [comment]
What is SDK Man?

**Comment by GrahamDumpleton** [comment]
Okay, presuming you mean https://sdkman.io/

**Comment by GrahamDumpleton** [comment]
In respect of extension packages for Java, the issue need to work out is best way to generate them under GitHub actions.

Because OCI images for imgpkg don't support multi arch, then need to have separate named images for amd64 and arm64. This is at least needed since JDK download is architecture dependent.

What I don't know is whether output from:

```
RUN mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app \
        -DarchetypeArtifactId=maven-archetype-quickstart \
        -DarchetypeVersion=1.4 -DinteractiveMode=false && \
    cd my-app && \
    mvn wrapper:wrapper

RUN gradle init && \
    gradle wrapper --gradle-version=7.4.2 --distribution-type=bin && \
    ./gradlew build
```

is also architecture independent.

If not, then can build on an amd64 runner under GitHub actions and reuse output of these from that build to also include in arm64 image. If there are arch specific files in what is generated from those steps, going to have to do some horrid stuff related to running docker under amd64 (QEMU) and copy results out of stopped container to then build imgpkg image.

**Comment by GrahamDumpleton** [comment]
As to jdk21-environment from next version of Educates, I can't remember if I have changed any interface between the base image and Educates. If not, is also possible that if add that image and do a tagged preview build, that one could use it in older Educates. Is possible that style theme overrides may not totally work as had to make minor tweaks in upgrading bootstrap version in newer Educates.

**Comment by billkable** [comment]
> In respect of extension packages for Java, the issue need to work out is best way to generate them under GitHub actions.
> 
> Because OCI images for imgpkg don't support multi arch, then need to have separate named images for amd64 and arm64. This is at least needed since JDK download is architecture dependent.
> 
> What I don't know is whether output from:
> 
> ```
> RUN mvn archetype:generate -DgroupId=com.mycompany.app -DartifactId=my-app \
>         -DarchetypeArtifactId=maven-archetype-quickstart \
>         -DarchetypeVersion=1.4 -DinteractiveMode=false && \
>     cd my-app && \
>     mvn wrapper:wrapper
> 
> RUN gradle init && \
>     gradle wrapper --gradle-version=7.4.2 --distribution-type=bin && \
>     ./gradlew build
> ```
> 
> is also architecture independent.
> 
> If not, then can build on an amd64 runner under GitHub actions and reuse output of these from that build to also include in arm64 image. If there are arch specific files in what is generated from those steps, going to have to do some horrid stuff related to running docker under amd64 (QEMU) and copy results out of stopped container to then build imgpkg image.

We've been using JDK17 with base image under both amd64 and arm64 (mac) without ill effect,
but we are not using the image install of maven or gradle (we use spring boot generate project wrappers).

Our custom java tools extension packages *are* platform dependent.  We built using github actions for amd64 given the primary use involved deployment on remote educates environments on containers/vms on amd.  We build primarily for arm64 for local developer use on Macos  The extension does does not change much, so far not too terrible of a tax for the manual build.

I have not yet tried out JDK 21 with new Boot features, to see if there is an impact.  I believe @robertmcnees is working on such a workshop now.  Perhaps I can work with him to test out in a custom base image.
