### ISSUE TITLE
Deleting educates when lookup-service resources exists prevent uninstallation of educates

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu-labs/educates-training-platform#536]
### Describe the bug

When you have a cluster with lookupService enabled and then create any resource for it (clusterconfig, tenantconfig or clientconfig) and this is still in the cluster, educates will not be removed because of finalizers on those resources.
Tested with educates installed via kapp-controller

**Comment by GrahamDumpleton** [comment]
This is possibly because we set up lookup service to watch crds for changes. When the crds get deleted, the lookup service says "okay I will not do anything about them now". Problem is that when the actual custom resources created from those crds are removed shortly after, the lookup service doesn't do anything and so doesn't remove the finalizers, possibly then blocking things.

**Comment by GrahamDumpleton** [comment]
Confirmed that it seems to be the CRD watching. Removing that seems to fix issue.
